version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: revieweat_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/revieweat
      - SECRET_KEY=your-secure-secret-key
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    container_name: revieweat_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revieweat
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
