name: Flutter CI  # 워크플로우 이름

on:
  push:
    branches: [main]  # main 브랜치에 push될 때 실행
  pull_request:
    branches: [main]  # main 브랜치로 PR 생성/수정 시 실행
  schedule:
    - cron: '0 15 * * *'  # 매일 한국 시간 자정(00:00)에 자동 실행

jobs:
  flutter-build:
    runs-on: ubuntu-latest  # 최신 우분투 환경에서 실행

    steps:
      - uses: actions/checkout@v3  # 저장소 코드 체크아웃

      - uses: subosito/flutter-action@v2  # Flutter SDK 설치
        with:
          flutter-version: '3.10.5'  # Flutter 버전 지정

      - name: Show Flutter and Dart version
        run: flutter --version  # Flutter, Dart 버전 확인

      - name: Install dependencies
        working-directory: frontend  # frontend 폴더 내에서 실행
        run: flutter pub get  # 패키지 의존성 설치

      - name: Analyze code
        working-directory: frontend  # frontend 폴더 내에서 실행
        run: flutter analyze  # 코드 정적 분석 수행

      - name: Run tests
        working-directory: frontend  # frontend 폴더 내에서 실행
        run: flutter test  # 단위 테스트 실행

      - name: Build debug APK
        working-directory: frontend  # frontend 폴더 내에서 실행
        run: flutter build apk --debug  # 디버그 모드 APK 빌드
